package ai

import (
	"encoding/json"
	"fmt"
)

// AIRequest describes one text-generation request.
type AIRequest struct {
	// Messages is the authoritative semantic request for every transport.
	Messages []Message
	// MaxTokens limits the number of tokens generated by the model.
	MaxTokens int
	// Tools lists provider-neutral function tools available to the model.
	Tools []ToolDefinition
	// ToolChoice controls whether and how the model may call tools.
	ToolChoice ToolChoice
	// ResponseFormat requests a structured response shape.
	ResponseFormat ResponseFormat
	// Reasoning configures model reasoning/thinking behavior when supported.
	Reasoning ReasoningConfig
}

// Validate checks request structure before provider-specific mapping.
func (r AIRequest) Validate() error {
	if err := r.ValidateMessages(); err != nil {
		return err
	}
	if err := r.ResponseFormat.Validate(); err != nil {
		return err
	}
	if err := r.ToolChoice.Validate(); err != nil {
		return err
	}
	for _, tool := range r.Tools {
		if err := tool.Validate(); err != nil {
			return err
		}
	}
	if len(r.Tools) == 0 && (r.ToolChoice.Mode != "" || len(r.ToolChoice.Names) != 0) {
		return fmt.Errorf("tool choice requires tools")
	}
	return nil
}

func (r AIRequest) ValidateMessages() error {
	if len(r.Messages) == 0 {
		return fmt.Errorf("request requires messages")
	}
	calls := map[string]string{}
	for _, m := range r.Messages {
		if err := m.Validate(); err != nil {
			return err
		}
		for _, p := range m.Parts {
			if p.ToolCall != nil {
				c := p.ToolCall
				if _, exists := calls[c.ID]; exists {
					return fmt.Errorf("duplicate tool call ID %q", c.ID)
				}
				calls[c.ID] = c.Name
			}
			if p.ToolResult != nil {
				v := p.ToolResult
				name, ok := calls[v.ToolCallID]
				if !ok || name != v.Name {
					return fmt.Errorf("unmatched or duplicate tool result %q", v.ToolCallID)
				}
				delete(calls, v.ToolCallID)
			}
		}
	}
	return nil
}

// Copy deep-copies every mutable request field.
func (r AIRequest) Copy() AIRequest {
	r.Messages = CloneMessages(r.Messages)
	r.Tools = append([]ToolDefinition(nil), r.Tools...)
	for i := range r.Tools {
		r.Tools[i].Parameters = append(json.RawMessage(nil), r.Tools[i].Parameters...)
	}
	r.ToolChoice.Names = append([]string(nil), r.ToolChoice.Names...)
	r.ResponseFormat.Schema = append(json.RawMessage(nil), r.ResponseFormat.Schema...)
	return r
}
