package ai

import (
	"context"
	"encoding/json"
	"fmt"
)

// AIResponse is the accumulated result of a non-streaming generation request.
type AIResponse struct {
	// Message contains the canonical semantic output.
	Message Message
	// Raw contains the provider response payload when retained by an implementation.
	Raw json.RawMessage
	// FinishReason identifies why the provider stopped generation when exposed.
	FinishReason string
	// InputTokens is the number of prompt tokens consumed by the model.
	InputTokens int
	// OutputTokens is the number of tokens generated by the model.
	OutputTokens int
	// ReasoningTokens is the number of reasoning/thought tokens reported by the model.
	ReasoningTokens int
}

// Usage is normalized provider token accounting for one completed request.
type Usage struct {
	InputTokens         int
	OutputTokens        int
	ReasoningTokens     int
	CachedTokens        int
	CacheCreationTokens int
	ToolUseTokens       int
}

// Add accumulates another provider usage record.
func (u *Usage) Add(other Usage) {
	u.InputTokens += other.InputTokens
	u.OutputTokens += other.OutputTokens
	u.ReasoningTokens += other.ReasoningTokens
	u.CachedTokens += other.CachedTokens
	u.CacheCreationTokens += other.CacheCreationTokens
	u.ToolUseTokens += other.ToolUseTokens
}

// Completion is terminal metadata emitted by a streaming provider request.
type Completion struct {
	Usage Usage
	// UsageReported distinguishes an absent provider usage block from a
	// provider-reported usage block whose counters are all zero.
	UsageReported bool
	FinishReason  string
	RequestID     string
	Provider      string
	Model         string
	Raw           json.RawMessage
}

// TokenType identifies the semantic kind of a streamed token.
type TokenType string

var (
	// TokenTypeText identifies user-visible generated text.
	TokenTypeText TokenType = "text"
	// TokenTypeThought identifies model reasoning content.
	TokenTypeThought TokenType = "thought"
	// TokenTypeToolCall identifies a structured request to invoke a tool.
	TokenTypeToolCall TokenType = "tool_call"
	// TokenTypeErr identifies an error emitted through the token stream.
	TokenTypeErr TokenType = "error"
	// TokenTypeCompletion identifies terminal provider metadata for a completed stream.
	TokenTypeCompletion TokenType = "completion"
	TokenTypePart       TokenType = "part"
)

// Token is one event emitted by Model.GenerateStream. Exactly one of Part, Err,
// and Completion is populated; accounting never becomes conversation content.
type Token struct {
	Part *ContentPart
	// TokenUsage is the output-token estimate attributed to this event.
	TokenUsage int
	Err        error
	Completion *Completion
}

// Validate checks that the event has one valid payload.
func (t Token) Validate() error {
	payloads := 0
	if t.Part != nil {
		payloads++
	}
	if t.Err != nil {
		payloads++
	}
	if t.Completion != nil {
		payloads++
	}
	if payloads != 1 {
		return fmt.Errorf("stream event requires exactly one payload")
	}
	if t.Part != nil {
		return (Message{Role: RoleAssistant, Parts: []ContentPart{*t.Part}}).Validate()
	}
	return nil
}

// Type derives the event kind from its payload.
func (t Token) Type() TokenType {
	if t.Err != nil {
		return TokenTypeErr
	}
	if t.Completion != nil {
		return TokenTypeCompletion
	}
	if t.Part != nil {
		switch t.Part.Kind {
		case ContentText, ContentJSON:
			return TokenTypeText
		case ContentReasoning:
			return TokenTypeThought
		case ContentToolCall:
			return TokenTypeToolCall
		}
	}
	return TokenTypePart
}

// Text returns text, reasoning, or structured JSON without exposing opaque state.
func (t Token) Text() string {
	if t.Part == nil {
		return ""
	}
	switch t.Part.Kind {
	case ContentText, ContentReasoning:
		return t.Part.Text
	case ContentJSON:
		return string(t.Part.JSON)
	}
	return ""
}

// ToolCall returns a detached view of the canonical call, or nil.
func (t Token) ToolCall() *ToolCall {
	if t.Part == nil || t.Part.Kind != ContentToolCall || t.Part.ToolCall == nil {
		return nil
	}
	call := t.Part.ToolCall.Clone()
	return &call
}

// SendToken forwards token unless ctx is canceled. It returns false when the
// receiver can no longer be reached because ctx ended.
func SendToken(ctx context.Context, out chan<- Token, token Token) bool {
	select {
	case out <- token:
		return true
	case <-ctx.Done():
		return false
	}
}

// Text returns user-visible response text.
func (r AIResponse) Text() string { return r.Message.Text() }

// Reasoning returns exposed reasoning text.
func (r AIResponse) Reasoning() string { return r.Message.Reasoning() }

// ToolCalls returns detached calls in their original order.
func (r AIResponse) ToolCalls() []ToolCall { return r.Message.ToolCalls() }

// SetMessage snapshots canonical output.
func (r *AIResponse) SetMessage(m Message) { r.Message = m.Clone() }

// AppendToken incorporates a streamed semantic delta and generation accounting.
func (r *AIResponse) AppendToken(t Token) {
	r.Message.AppendToken(t)
	if t.Part != nil && t.Part.Kind == ContentReasoning {
		r.ReasoningTokens += t.TokenUsage
	}
	if t.Completion != nil {
		if t.Completion.UsageReported {
			r.InputTokens = t.Completion.Usage.InputTokens
			r.OutputTokens = t.Completion.Usage.OutputTokens
			r.ReasoningTokens = t.Completion.Usage.ReasoningTokens
		}
		r.FinishReason = t.Completion.FinishReason
		r.Raw = append(r.Raw[:0], t.Completion.Raw...)
		return
	}
	r.OutputTokens += t.TokenUsage
}

// AppendToken appends ordered semantic deltas. Stream errors and completion
// accounting are execution metadata and never become conversation text.
func (m *Message) AppendToken(t Token) {
	if t.Part == nil {
		return
	}
	p := CloneParts([]ContentPart{*t.Part})[0]
	if m.Role == "" {
		m.Role = RoleAssistant
	}
	if n := len(m.Parts); n > 0 && (p.Kind == ContentText || p.Kind == ContentReasoning) && m.Parts[n-1].Kind == p.Kind {
		last := &m.Parts[n-1]
		if p.Text == "" && len(p.Extensions) > 0 && len(last.Extensions) == 0 {
			last.Extensions = append(last.Extensions, p.Extensions...)
			return
		}
		if len(last.Extensions) == 0 && len(p.Extensions) == 0 {
			last.Text += p.Text
			return
		}
	}
	m.Parts = append(m.Parts, p)
}

// Clone detaches every mutable payload in a stream event.
func (t Token) Clone() Token {
	if t.Part != nil {
		p := CloneParts([]ContentPart{*t.Part})[0]
		t.Part = &p
	}
	if t.Completion != nil {
		c := *t.Completion
		c.Raw = append(json.RawMessage(nil), c.Raw...)
		t.Completion = &c
	}
	return t
}
