package ai

import (
	"context"
	"encoding/json"
)

// AIResponse is the accumulated result of a non-streaming generation request.
type AIResponse struct {
	// Message is the authoritative semantic output; convenience fields are projections.
	Message Message
	// Text contains the generated response text.
	Text string
	// Reasoning contains model reasoning/thinking text when exposed separately.
	Reasoning string
	// ToolCalls contains structured tool calls produced by the model.
	ToolCalls []ToolCall
	// Raw contains the provider response payload when retained by an implementation.
	Raw json.RawMessage
	// FinishReason identifies why the provider stopped generation when exposed.
	FinishReason string
	// InputTokens is the number of prompt tokens consumed by the model.
	InputTokens int
	// OutputTokens is the number of tokens generated by the model.
	OutputTokens int
	// ReasoningTokens is the number of reasoning/thought tokens reported by the model.
	ReasoningTokens int
}

// Usage is normalized provider token accounting for one completed request.
type Usage struct {
	InputTokens         int
	OutputTokens        int
	ReasoningTokens     int
	CachedTokens        int
	CacheCreationTokens int
	ToolUseTokens       int
}

// Add accumulates another provider usage record.
func (u *Usage) Add(other Usage) {
	u.InputTokens += other.InputTokens
	u.OutputTokens += other.OutputTokens
	u.ReasoningTokens += other.ReasoningTokens
	u.CachedTokens += other.CachedTokens
	u.CacheCreationTokens += other.CacheCreationTokens
	u.ToolUseTokens += other.ToolUseTokens
}

// Completion is terminal metadata emitted by a streaming provider request.
type Completion struct {
	Usage Usage
	// UsageReported distinguishes an absent provider usage block from a
	// provider-reported usage block whose counters are all zero.
	UsageReported bool
	FinishReason  string
	RequestID     string
	Provider      string
	Model         string
	Raw           json.RawMessage
}

// TokenType identifies the semantic kind of a streamed token.
type TokenType string

var (
	// TokenTypeText identifies user-visible generated text.
	TokenTypeText TokenType = "text"
	// TokenTypeThought identifies model reasoning content.
	TokenTypeThought TokenType = "thought"
	// TokenTypeToolCall identifies a structured request to invoke a tool.
	TokenTypeToolCall TokenType = "tool_call"
	// TokenTypeErr identifies an error emitted through the token stream.
	TokenTypeErr TokenType = "error"
	// TokenTypeCompletion identifies terminal provider metadata for a completed stream.
	TokenTypeCompletion TokenType = "completion"
	TokenTypePart       TokenType = "part"
)

// Token is one event emitted by Model.GenerateStream.
//
// Data contains the raw provider payload for text-like tokens. Text contains
// normalized text when the provider exposes it separately. ToolCall and Err are
// populated for their corresponding token types.
type Token struct {
	// Part carries a canonical semantic delta. When non-nil it takes precedence
	// over Text/Data/ToolCall for conversation accumulation.
	Part *ContentPart
	// Type identifies how the token should be interpreted.
	Type TokenType
	// Data contains the token's raw byte representation.
	Data []byte
	// TokenUsage is the output-token usage attributed to this event.
	TokenUsage int

	// ToolCall contains the structured call for TokenTypeToolCall.
	ToolCall *ToolCall
	// Text contains normalized text when available.
	Text string
	// Err contains the stream error for TokenTypeErr.
	Err error
	// Completion contains terminal provider metadata for TokenTypeCompletion.
	Completion *Completion
}

// String returns the token's raw Data as a string.
func (t Token) String() string {
	return string(t.Data)
}

// SendToken forwards token unless ctx is canceled. It returns false when the
// receiver can no longer be reached because ctx ended.
func SendToken(ctx context.Context, out chan<- Token, token Token) bool {
	select {
	case out <- token:
		return true
	case <-ctx.Done():
		return false
	}
}

// SetMessage snapshots canonical output and refreshes compatibility projections.
func (r *AIResponse) SetMessage(m Message) {
	r.Message = m.Clone()
	r.Text = r.Message.Text()
	r.Reasoning = r.Message.Reasoning()
	r.ToolCalls = r.Message.ToolCalls()
}

// AppendToken incorporates a streamed semantic delta and generation accounting.
func (r *AIResponse) AppendToken(t Token) {
	r.Message.AppendToken(t)
	r.Text = r.Message.Text()
	r.Reasoning = r.Message.Reasoning()
	r.ToolCalls = r.Message.ToolCalls()
	if (t.Part != nil && t.Part.Kind == ContentReasoning) || (t.Part == nil && t.Type == TokenTypeThought) {
		r.ReasoningTokens += t.TokenUsage
	}
	if t.Type == TokenTypeCompletion {
		if t.Completion != nil {
			if t.Completion.UsageReported {
				r.InputTokens = t.Completion.Usage.InputTokens
				r.OutputTokens = t.Completion.Usage.OutputTokens
				r.ReasoningTokens = t.Completion.Usage.ReasoningTokens
			}
			r.FinishReason = t.Completion.FinishReason
			r.Raw = append(r.Raw[:0], t.Completion.Raw...)
		}
		return
	}
	r.OutputTokens += t.TokenUsage
}

// AppendToken appends ordered semantic deltas. Stream errors and completion
// accounting are execution metadata and never become conversation text.
func (m *Message) AppendToken(t Token) {
	var p ContentPart
	if t.Part != nil {
		p = CloneParts([]ContentPart{*t.Part})[0]
	} else {
		text := t.Text
		if text == "" {
			text = string(t.Data)
		}
		switch t.Type {
		case TokenTypeText:
			p = ContentPart{Kind: ContentText, Text: text}
		case TokenTypeThought:
			p = ContentPart{Kind: ContentReasoning, Text: text}
		case TokenTypeToolCall:
			if t.ToolCall == nil {
				return
			}
			c := t.ToolCall.Clone()
			p = ContentPart{Kind: ContentToolCall, ToolCall: &c}
		default:
			return
		}
	}
	if m.Role == "" {
		m.Role = RoleAssistant
	}
	if n := len(m.Parts); n > 0 && (p.Kind == ContentText || p.Kind == ContentReasoning) && m.Parts[n-1].Kind == p.Kind {
		last := &m.Parts[n-1]
		if p.Text == "" && len(p.Extensions) > 0 {
			last.Extensions = append(last.Extensions, p.Extensions...)
			return
		}
		if len(last.Extensions) == 0 && len(p.Extensions) == 0 {
			last.Text += p.Text
			return
		}
	}
	m.Parts = append(m.Parts, p)
}

// Clone detaches every mutable payload in a stream event.
func (t Token) Clone() Token {
	t.Data = append([]byte(nil), t.Data...)
	if t.Part != nil {
		p := CloneParts([]ContentPart{*t.Part})[0]
		t.Part = &p
	}
	if t.ToolCall != nil {
		c := t.ToolCall.Clone()
		t.ToolCall = &c
	}
	if t.Completion != nil {
		c := *t.Completion
		c.Raw = append(json.RawMessage(nil), c.Raw...)
		t.Completion = &c
	}
	return t
}

// Normalized snapshots a token and derives legacy views solely from Part when
// present. Stale compatibility fields cannot trigger tools or expose old text.
func (t Token) Normalized() Token {
	t = t.Clone()
	if t.Part == nil {
		return t
	}
	t.Type = TokenTypePart
	t.Text = ""
	t.Data = nil
	t.ToolCall = nil
	switch t.Part.Kind {
	case ContentText:
		t.Type = TokenTypeText
		t.Text = t.Part.Text
	case ContentReasoning:
		t.Type = TokenTypeThought
		t.Text = t.Part.Text
	case ContentToolCall:
		t.Type = TokenTypeToolCall
		if t.Part.ToolCall != nil {
			c := t.Part.ToolCall.Clone()
			t.ToolCall = &c
		}
	}
	return t
}
